name: rollerfeet.com(b)
favicon: null
layout_spectrum: 0.7721405168995261
typography_spectrum: 0.5394135424867272
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.91731067141518
  lightness: 0.9251244403421879
  saturation: 0.7882965211756527
  rhythmicContrast: 0.5769920216407627
purpose: []
