name: rollerfeet.com(b)
favicon: null
layout_spectrum: 0.19411
typography_spectrum: 0.00289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9bd2bb'
    - '#f7f7f7'
    - '#517c69'
    - '#304246'
    - '#7c5456'
  brandStrength: 0
  lightness: 0
  saturation: 0.7882965211756527
  rhythmicContrast: 1
purpose: []
